from class_file import *

root=Node('a',[])
b=Node('b',[])
c=Node('c',[])
d=Node('d',[])
e=Node('e',[])
f=Node('f',[])
g=Node('g',[])
h=Node('h',[])
i=Node('i',[])
j=Node('j',[])
k=Node('k',[])
l=Node('l',[])
m=Node('m',[])
n=Node('n',[])
o=Node('o',[])
p=Node('p',[])
q=Node('q',[])
r=Node('r',[])
s=Node('s',[])
t=Node('t',[])
u=Node('u',[])

root.add_child(list([b,c,d]))
b.add_child(list([e,f]))
c.add_child(list([g,h]))
d.add_child(list([i,j]))
e.add_child(list([k,l]))
f.add_child(list([m]))
g.add_child(list([n]))
h.add_child(list([o]))
i.add_child(list([p,q]))
j.add_child(list([r]))
k.add_child(list([s]))
l.add_child(list([t]))
p.add_child(list([u]))

path_BFS=BFS(root,'a','n',[])
result,path_DFS=DFS(root,'a','n',[])


print("----------------------------------------------------------------")
print("In BFS the path is : "+"->".join(str(x) for x in path_BFS) )
print("total visited_nodes in BFS is :"+str(len(path_BFS)))
print("--------------------------------------------------------")
print("In DFS the path is : "+"->".join(str(x) for x in path_DFS) )
print("total visited_nodes in DFS is:"+str(len(path_DFS)))
print("---------------------------------------------------------")
